#ifndef __LOOM_INTERPRETER_ARGUMENTS_HPP__
#define __LOOM_INTERPRETER_ARGUMENTS_HPP__

#define _DEBUG_SIMPLE_
//#define _DEBUG_ADVANCED_
//#define _DISPLAY_ENTRY_
//#define _DISPLAY_ARGS_
//#define _STAT_THREADS_
#define _TIME_PROGRAM_

#endif//__LOOM_INTERPRETER_ARGUMENTS_HPP__
